name: Tests

on: [ push ]

jobs:
  ci:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          -
            name: Default
            ruby: 2.7.6
            gemfile: Gemfile
            rails_version: 5.2
          -
            ruby: 2.7.6
            gemfile: gemfiles/Gemfile.5.2-2.7.gemfile
            rails_version: 5.2

    env:
      BUNDLE_GEMFILE: "${{ matrix.gemfile }}"
      BUNDLE_WITHOUT: production
      BUNDLE_JOBS: 3
      BUNDLE_RETRY: 3

    steps:
      -
        name: Checkout Source Code
        uses: actions/checkout@v3
        with:
          fetch-depth: '1'
      -
        name: Install ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      -
        name: Bundle ${{ matrix.gemfile }}
        run: bundle install
      -
        name: Dummy Setup Rails ${{ matrix.rails_version }}
        run: bundle exec bin/setup
      -
        name: Run migrations
        run: bin/rails db:migrate RAILS_ENV=test
      -
        name: Run test suite Rails ${{ matrix.rails_version }}
        run: bundle exec rake
