name: Tests

on: [ push ]

env:
  BUNDLE_WITHOUT: production
  BUNDLE_JOBS: 3
  BUNDLE_RETRY: 3
  SECRET_KEY_BASE: abcd1234

jobs:
  ci:

    name: Test ${{ matrix.name }}

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          -
            name: Rails 5.x
            ruby: 2.7.6
            gemfile: gemfiles/Gemfile.5.2.8.gemfile
            rails_version: 5.2.8
          -
            name: Rails 6.x
            ruby: 2.7.6
            gemfile: gemfiles/Gemfile.6.1.6.gemfile
            rails_version: 6.1.6
          -
            name: Rails 7.x
            ruby: 2.7.6
            gemfile: gemfiles/Gemfile.7.0.3.gemfile
            rails_version: 7.0.3

    env:
      BUNDLE_GEMFILE: "${{ matrix.gemfile }}"

    steps:
      -
        name: Test Envs
        run: echo ${{ jobs.ci.env.BUNDLE_GEMFILE }}
