name: Tests

on: [ push ]

env:
  BUNDLE_WITHOUT: production
  BUNDLE_JOBS: 3
  BUNDLE_RETRY: 3

jobs:
  ci:

    name: Test ${{ matrix.name }}

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          -
            name: Rails 5.x
            ruby: 2.7.6
            gemfile: gemfiles/Gemfile.5.2.8.gemfile
            rails_version: 5.2.8
          -
            name: Rails 6.x
            ruby: 2.7.6
            gemfile: gemfiles/Gemfile.6.1.6.gemfile
            rails_version: 6.1.6
          -
            name: Rails 7.x
            ruby: 2.7.6
            gemfile: gemfiles/Gemfile.7.0.3.gemfile
            rails_version: 7.0.3

    env:
      BUNDLE_GEMFILE: "${{ matrix.gemfile }}"

    steps:
      -
        name: Checkout Source Code
        uses: actions/checkout@v3
        with:
          fetch-depth: '1'
      -
        name: Install ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      -
        name: Bundle install extra gems
        run: |
          gem install tty-command
          gem install tty-option
      -
        name: Bundle install ${{ matrix.gemfile }}
        run: BUNDLE_GEMFILE=${{ env.BUNDLE_GEMFILE }} bundle install
      -
        name: Setup Tests For Rails ${{ matrix.rails_version }}
        run: BUNDLE_GEMFILE=${{ env.BUNDLE_GEMFILE }} ./bin/setup
      -
        name: Test Active Storage ${{ matrix.rails_version }}
        run: |
          cd ActiveStorageOverTime
          BUNDLE_GEMFILE=../${{ env.BUNDLE_GEMFILE }} bundle exec rails test